# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      addons_skunk_ci_test_db:
        image: postgres
        env:
          POSTGRES_USER: ${{secrets.ADDONS_SKUNK_DB_CONFIG_USER}}
          POSTGRES_PASSWORD: ${{secrets.ADDONS_SKUNK_DB_CONFIG_PASSWORD}}
          POSTGRES_DB: addons_skunk_ci_test
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Run tests
      env:
        ADDONS_SKUNK_DB_CONFIG_HOST: localhost
        ADDONS_SKUNK_DB_CONFIG_PORT: 5432
        ADDONS_SKUNK_DB_CONFIG_USER: ${{secrets.ADDONS_SKUNK_DB_CONFIG_USER}}
        ADDONS_SKUNK_DB_CONFIG_PASSWORD: ${{secrets.ADDONS_SKUNK_DB_CONFIG_PASSWORD}}
        ADDONS_SKUNK_DB_CONFIG_DATABASE: addons_skunk_ci_test
      run: sbt test
